### PR TITLE
Removed all remnants of Pi Points, Bones, Job Reqs, and Probation

### PR DESCRIPTION
**Pull request by co1in**

### CODE REVIEW

**Comment by austintrose** [comment]
I recommend you delete all of the "'something_auto_something.py" migrations files, then run the `makemigrations` command once more to generate a single file encompassing all of the migrations. This isn't strictly necessary, it's just convenient. Especially if you end up needing to un-apply the migration (please god no).

**Comment by co1in** [comment]
I did that partially to ensure the foreign keys to Bones were deleted
before the Bones model was deleted, since it appears that django does
cascading deletes.

**Comment by kdmccormick** [comment]
Can you change the "Archive" button to say  "Accept"? It being called "Archive" makes it seem like "Reject" will not archive it.

**Comment by kdmccormick** [comment]
Other than that, looks good :+1:

**Pull request merged**
